language: java

jdk:
- openjdk11

os:
- linux

dist: xenial

env:
- GRAALVM_VERSION="20.1.0"

cache:
  directories:
  - $HOME/.m2
  - $HOME/graalvm

install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then DOWNLOAD_OS_NAME="darwin"; fi
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then DOWNLOAD_OS_NAME="linux"; fi
  if ! test -e "graalvm/graalvm-ce-java11-$GRAALVM_VERSION"; then
    mkdir -pv graalvm
    cd graalvm
    curl -LJ "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-java11-$DOWNLOAD_OS_NAME-amd64-$GRAALVM_VERSION.tar.gz" --output graalvm.tar.gz
    tar -xzf graalvm.tar.gz
    cd
    graalvm/graalvm-ce-java11-$GRAALVM_VERSION/bin/gu install native-image
  else
    true
  fi
- export JAVA_HOME="$(pwd)/graalvm/graalvm-ce-java11-$GRAALVM_VERSION" && if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME="$JAVA_HOME/Contents/Home"; fi
- mvn --batch-mode --show-version clean install -P quick

script:
- export JAVA_HOME="$(pwd)/graalvm/graalvm-ce-java11-$GRAALVM_VERSION" && if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME="$JAVA_HOME/Contents/Home"; fi
- mvn --batch-mode --show-version clean verify
