language: java

jdk:
- openjdk11

os:
- linux

dist: xenial

env:
- GRAALVM_VERSION="20.1.0"

cache:
  directories:
  - $HOME/.m2
  - $HOME/graalvm

install:
- scripts/travis_install.sh
- export JAVA_HOME="$HOME/graalvm/graalvm-ce-java11-$GRAALVM_VERSION" && if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME="$JAVA_HOME/Contents/Home"; fi
- mvn --batch-mode --show-version clean install -P quick

script:
- export JAVA_HOME="$HOME/graalvm/graalvm-ce-java11-$GRAALVM_VERSION" && if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME="$JAVA_HOME/Contents/Home"; fi
- mvn --batch-mode --show-version clean verify
